#ifndef CONSTANTS_GLSL
#define CONSTANTS_GLSL

const uint VERTEX_ATTRIB_POS_LOCATION					= 0U;
const uint VERTEX_ATTRIB_UV_LOCATION					= 1U;
const uint VERTEX_ATTRIB_NORMAL_LOCATION				= 2U;
const uint VERTEX_ATTRIB_COLOR_LOCATION					= 3U;
const uint VERTEX_ATTRIB_TANGENT_LOCATION				= 4U;

const uint VERTEX_ATTRIB_POS_BIT						= (1U << VERTEX_ATTRIB_POS_LOCATION);
const uint VERTEX_ATTRIB_UV_BIT							= (1U << VERTEX_ATTRIB_UV_LOCATION);
const uint VERTEX_ATTRIB_NORMAL_BIT						= (1U << VERTEX_ATTRIB_NORMAL_LOCATION);
const uint VERTEX_ATTRIB_COLOR_BIT						= (1U << VERTEX_ATTRIB_COLOR_LOCATION);
const uint VERTEX_ATTRIB_TANGENT_BIT					= (1U << VERTEX_ATTRIB_TANGENT_LOCATION);

// Descriptor set locations
const uint MATERIALS_DESC_SET_LOCATION					= 0U;
const uint SAMPLED_IMAGES_DESC_SET_LOCATION				= 1U;
const uint SUB_LAYER_DESC_SET_LOCATION					= 2U;
const uint RENDERER_DESC_SET_LOCATION					= 3U;

// Descriptor locations

// Global
const uint MATERIAL_DESC_SIMPLE_MATERIAL_LOCATION		= 0U;
const uint MATERIAL_DESC_IMAGE_MATERIAL_LOCATION		= 1U;
const uint MATERIAL_DESC_TRANSFORM_MATERIAL_LOCATION	= 2U;
const uint MATERIAL_DESC_PHONG_MATERIAL_LOCATION		= 3U;

// Sub layer
const uint SUB_LAYER_DESC_INSTANCE_INFO_LOCATION		= 0U;

#endif